### ISSUE TITLE
Crowd the world

### ISSUE THREAD

**Issue by chassain** [mykle1/MMM-Census#1]
hello,

i have just "crowd the world" when i use your module.
What's the problem (i m using your config.js) ?
thanks

**Comment by ryanslinger** [comment]
i have the same issue and i tried to fix it but i gave up after some time

**Comment by JanZamoyski** [comment]
I'm having the same issue...

**Comment by Duncan19790** [comment]
Same here, anyone here to support?

**Comment by mykle1** [comment]
The api has changed. It was free without an api key. Now, you have to sign up, which I did. Now I'm waiting to hear from them. What a pain in the ass!
